#!/usr/bin/env python3
"""Write Gen 1-5 base stats used to calculate battle stats.

Reads the PokeAPI pokemon and pokemon_stats tables. Alternate formes that
change base stats in Generation 4 and 5 are stored beside the national-dex row.
"""

import csv
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "tools" / "cache"
OUT = ROOT / "source" / "base_stats.inc"

POKEMON_URL = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon.csv"
STATS_URL = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon_stats.csv"

# Game form index for formes whose base stats can differ. Mega and regional
# formes are intentionally absent: those bytes do not appear in Gen 3-5 saves.
FORMS = (
    ("deoxys-attack", 386, 1),
    ("deoxys-defense", 386, 2),
    ("deoxys-speed", 386, 3),
    ("wormadam-sandy", 413, 1),
    ("wormadam-trash", 413, 2),
    ("rotom-heat", 479, 1),
    ("rotom-wash", 479, 2),
    ("rotom-frost", 479, 3),
    ("rotom-fan", 479, 4),
    ("rotom-mow", 479, 5),
    ("giratina-origin", 487, 1),
    ("shaymin-sky", 492, 1),
    ("darmanitan-zen", 555, 1),
    ("tornadus-therian", 641, 1),
    ("thundurus-therian", 642, 1),
    ("landorus-therian", 645, 1),
    ("kyurem-white", 646, 1),
    ("kyurem-black", 646, 2),
    ("meloetta-pirouette", 648, 1),
)


def load_csv(name, url):
    path = CACHE / name
    if not path.exists():
        CACHE.mkdir(parents=True, exist_ok=True)
        urllib.request.urlretrieve(url, path)
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def main():
    pokemon = load_csv("pokemon.csv", POKEMON_URL)
    stats_rows = load_csv("pokemon_stats.csv", STATS_URL)

    by_id = {}
    species_of = {}
    for row in pokemon:
        pid = int(row["id"])
        by_id[row["identifier"]] = pid
        species_of[pid] = int(row["species_id"])

    stats = {}
    for row in stats_rows:
        pid = int(row["pokemon_id"])
        slot = int(row["stat_id"]) - 1
        if 0 <= slot < 6:
            stats.setdefault(pid, [0, 0, 0, 0, 0, 0])[slot] = int(row["base_stat"])

    base = [[0, 0, 0, 0, 0, 0] for _ in range(650)]
    for pid, species in species_of.items():
        if 1 <= species <= 649 and pid == species:
            base[species] = stats[pid]

    if base[1] != [45, 49, 49, 65, 65, 45]:
        raise SystemExit("Bulbasaur base stats did not match")
    if base[25] != [35, 55, 40, 50, 50, 90]:
        raise SystemExit("Pikachu base stats did not match")
    if base[649] != [71, 120, 95, 120, 95, 99]:
        raise SystemExit("Genesect base stats did not match")

    forms = []
    for identifier, species, form in FORMS:
        pid = by_id[identifier]
        if species_of[pid] != species:
            raise SystemExit(f"{identifier} is not species {species}")
        row = stats[pid]
        if row != base[species]:
            forms.append((species, form, row))

    lines = [
        "/* Generated by tools/build_basestats.py. HP, Attack, Defense, Sp. Atk, Sp. Def, Speed. */",
        "static const uint8_t base_stats[650][6] = {",
    ]
    for species, row in enumerate(base):
        lines.append("    {%3d, %3d, %3d, %3d, %3d, %3d}," % tuple(row))
    lines.append("};")
    lines.append("")
    lines.append("static const struct {")
    lines.append("    uint16_t species;")
    lines.append("    uint8_t form;")
    lines.append("    uint8_t stats[6];")
    lines.append("} form_stats[] = {")
    for species, form, row in forms:
        nums = ", ".join(str(n) for n in row)
        lines.append(f"    {{{species}, {form}, {{{nums}}}}},")
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(forms)} forme rows)")


if __name__ == "__main__":
    main()
