#include "flavor.h"

/* Generated by tools/build_flavor.py from Black, then earlier, Pokedex text. */
static const char *const flavor_text[650] = {
#include "flavor.inc"
};

const char *species_flavor(unsigned species)
{
    if (species >= 650)
        return "";
    return flavor_text[species];
}
